package org.opensolaris.opengrok.analysis.spbdl;

import java.util.HashSet;
import java.util.Set;

/**
  * Holds static hash set containing the BDL keywords
  */
public class Consts {
    public static final Set<String> kwd = new HashSet<String>() ;
    static {
    	kwd.add( "ALL" );
    	kwd.add( "BEGIN" );
    	kwd.add( "BENCHMARK" );
    	kwd.add( "RNDBIN" );
    	kwd.add( "CHR" );
    	kwd.add( "COMMIT" );
    	kwd.add( "DATABASE" );
    	kwd.add( "DCLRAND" );
    	kwd.add( "DCLTRANS" );
    	kwd.add( "DCLUSER" );
    	kwd.add( "DCLSQL" );
    	kwd.add( "DO" );
    	kwd.add( "ELSE" );
    	kwd.add( "END" );
    	kwd.add( "EOS" );
    	kwd.add( "EXIT" );
    	kwd.add( "RNDEXPF" );
    	kwd.add( "RNDEXPN" );
    	kwd.add( "FETCH" );
    	kwd.add( "FOR" );
    	kwd.add( "RNDUNIN" );
    	kwd.add( "RNDSTR" );
    	kwd.add( "RNDUNII" );
    	kwd.add( "RNDUNIF" );
    	kwd.add( "IF" );
    	kwd.add( "IN" );
    	kwd.add( "INIT" );
    	kwd.add( "INTO" );
    	kwd.add( "RNDIND" );
    	kwd.add( "LAST" );
    	kwd.add( "RNDSNO" );
    	kwd.add( "LOOP" );
    	kwd.add( "MOD" );
    	kwd.add( "NEXT" );
    	kwd.add( "NOT" );
    	kwd.add( "ORD" );
    	kwd.add( "OUT" );
    	kwd.add( "RETURN" );
    	kwd.add( "ROLLBACK" );
    	kwd.add( "ROW" );
    	kwd.add( "SET" );
    	kwd.add( "STORED" );
    	kwd.add( "THEN" );
    	kwd.add( "TRANSACTION" );
    	kwd.add( "TRANSACTIONS" );
    	kwd.add( "UNIQUE" );
    	kwd.add( "USER" );
    	kwd.add( "VAR" );
    	kwd.add( "WAIT" );
    	kwd.add( "WHILE" );
    	kwd.add( "RESULT" );
    	kwd.add( "TO" );
    	kwd.add( "OR" );
    	kwd.add( "AND" );
    	kwd.add( "OF" );
    	kwd.add( "ARRAY" );
    	kwd.add( "WRITE" );
    	kwd.add( "WRITELN" );
    	kwd.add( "ROWS" );
    	kwd.add( "RC" );
    	kwd.add( "CONST" );
    	kwd.add( "DCLFUNC" );
    	kwd.add( "FUNCTION" );
    	kwd.add( "RNDPERN" );
    	kwd.add( "RESET" );
    	kwd.add( "RNDFILE" );
    	kwd.add( "ELSEIF" );
    	kwd.add( "RNDSTREAM" );
    	kwd.add( "SELECT" );
    	kwd.add( "INSERT" );
    	kwd.add( "UPDATE" );
    	kwd.add( "DELETE" );
    	kwd.add( "CURRENT" );
    	kwd.add( "PROC" );
    	kwd.add( "INOUT" );
    	kwd.add( "DLL" );
    	kwd.add( "CURSOR" );
    	kwd.add( "SQL" );
    	kwd.add( "PTR" );
    	kwd.add( "USE" );
    	kwd.add( "HALT" );
    	kwd.add( "DCLFORM" );
    	kwd.add( "FORM" );
    	kwd.add( "SIZEOF" );
    	kwd.add( "OPTIONAL" );
    	kwd.add( "DCLEVENT" );
    	kwd.add( "HANDLER" );
    	kwd.add( "THROW" );
    	kwd.add( "DSTRING" );
    	kwd.add( "DCLPARAM" );
    	kwd.add( "LENSPEC" );
    	kwd.add( "SIZESPEC" );
    	kwd.add( "ALLOWNULL" );
    	kwd.add( "EXPLICIT" );
    	kwd.add( "UNION" );
    	kwd.add( "BIN" );
    }
}
